name: Build ElaWidgetTool (Qt6.7 + VS2022)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # 安装 Qt 6.7.0 for MSVC2022 64-bit
    - name: Install Qt 6.7
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.7.0'          
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: ''

    - name: Configure CMake
      run: |
        cmake -S . -B build ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DCMAKE_PREFIX_PATH="${{ env.Qt6_Dir }}" ^
          -DCMAKE_INSTALL_PREFIX="./install" ^
          -DBUILD_SHARED_LIBS=ON ^
          -G "Visual Studio 17 2022" -A x64

    - name: Build and Install
      run: |
        cmake --build build --config Release --target INSTALL --parallel 4

    - name: Package Binaries
      run: |
        mkdir release_package
        Copy-Item -Recurse -Path "install/include" -Destination "release_package/"
        Copy-Item -Path "install/lib/*.lib" -Destination "release_package/"
        Copy-Item -Path "install/bin/*.dll" -Destination "release_package/"
        Compress-Archive -Path "release_package/*" -DestinationPath "ElaWidgetTool-Qt6.7-MSVC2022.zip"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ElaWidgetTool-Binaries
        path: ElaWidgetTool-Qt6.7-MSVC2022.zip
